In [ ]:
import numpy as np

In [ ]:
# 1.

inp=np.array([1,2,3,4,5])
np.vander(inp,6)

array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [3125,  625,  125,   25,    5,    1]])

In [ ]:
np.vander(inp,6,True)

array([[   1,    1,    1,    1,    1,    1],
       [   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    5,   25,  125,  625, 3125]])

In [ ]:
# another way
def vendermonde_matrix(inp_vector,N,increasing=False):
    if increasing==False:
        a=np.mat([x**(N-i-1) for x in inp_vector for i in  range(N)]).reshape(len(inp_vector),N)
        return a
    else:
        if increasing==True:
            b=np.mat([x**i for x in inp_vector for i in range(N)]).reshape(len(inp_vector),N)
            return b

In [ ]:
vendermonde_matrix([1,2,3,4],5)

matrix([[  1,   1,   1,   1,   1],
        [ 16,   8,   4,   2,   1],
        [ 81,  27,   9,   3,   1],
        [256,  64,  16,   4,   1]])

In [ ]:
vendermonde_matrix([1,2,3,4],5,True)

matrix([[  1,   1,   1,   1,   1],
        [  1,   2,   4,   8,  16],
        [  1,   3,   9,  27,  81],
        [  1,   4,  16,  64, 256]])

In [ ]:
# 2.

def moving_average(a, n=3) :
    l = np.cumsum(a, dtype=float)
    l[n:] = l[n:] - l[:-n]
    return l[n - 1:] / n

In [ ]:
moving_average([10,20,30,40,50,60,70,80,90,100],4)


array([25., 35., 45., 55., 65., 75., 85.])

In [ ]:
moving_average([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])